#!/bin/bash

HERE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

source $HERE/platform_validator.sh
source $HERE/program_validator.sh
source $HERE/definitions.sh

PPRO_PLATFORM_PROGRAM_COMMAND_RUN_VENV_PYTHON=""
PPRO_PLATFORM_PROGRAM_ACTIVATE_VENV=""
PPRO_MARKET_ENGINE_ASSETS_DEMANGLED_PATH=""
PPRO_CLIENT_LAUNCHER_BUILD=""
PPRO_CLIENT_APPLICATION_BUILD=""
PPRO_CLIENT_SONAR_BUILD=""
PPRO_CLIENT_ENGINE_BUILD=""
PPRO_CLIENT_ENGINE_BINARY=""
PPRO_API_LAUNCHER_BUILD=""
PPRO_API_SONAR_BUILD=""
PPRO_ZIP_DIR_PATH=""
PPRO_ZIP_ARCHIVE_PATH=""

if [[ $ARG_PLATFORM == $PLATFORM_LINUX_X86_64 ]]; then
    PPRO_MARKET_ENGINE_ASSETS_DEMANGLED_PATH=$MARKET_ENGINE_ASSETS_PATH
    PPRO_CLIENT_LAUNCHER_BUILD=$CLIENT_LAUNCHER_BUILD_X86_64_LINUX
    PPRO_CLIENT_APPLICATION_BUILD=$CLIENT_APPLICATION_BUILD_X86_64_LINUX
    PPRO_CLIENT_SONAR_BUILD=$CLIENT_SONAR_BUILD_X86_64_LINUX
    PPRO_CLIENT_ENGINE_BUILD=$CLIENT_ENGINE_BUILD_X86_64_LINUX
    PPRO_CLIENT_ENGINE_BINARY=$MARKET_ENGINE_CLIENT_TRADEUP_ENGINE/build/build_linux64/calculator
    PPRO_API_LAUNCHER_BUILD=$API_LAUNCHER_BUILD_X86_64_LINUX
    PPRO_API_SONAR_BUILD=$API_SONAR_BUILD_X86_64_LINUX
elif [[ $ARG_PLATFORM == $PLATFORM_WINDOWS_X86_64 ]]; then
    PPRO_MARKET_ENGINE_ASSETS_DEMANGLED_PATH="$(echo $MARKET_ENGINE_ASSETS_PATH | sed -E 's|^/([a-zA-Z])/|\U\1:/|')"
    PPRO_CLIENT_LAUNCHER_BUILD=$CLIENT_LAUNCHER_BUILD_X86_64_WINDOWS
    PPRO_CLIENT_APPLICATION_BUILD=$CLIENT_APPLICATION_BUILD_X86_64_WINDOWS
    PPRO_CLIENT_SONAR_BUILD=$CLIENT_SONAR_BUILD_X86_64_WINDOWS
    PPRO_CLIENT_ENGINE_BUILD=$CLIENT_ENGINE_BUILD_X86_64_WINDOWS
    PPRO_CLIENT_ENGINE_BINARY=$MARKET_ENGINE_CLIENT_TRADEUP_ENGINE/build/build_win64/calculator
    PPRO_API_LAUNCHER_BUILD=$API_LAUNCHER_BUILD_X86_64_WINDOWS
    PPRO_API_SONAR_BUILD=$API_SONAR_BUILD_X86_64_WINDOWS
fi

# LINUX + CLIENT
if [[ $ARG_PLATFORM == $PLATFORM_LINUX_X86_64 && $ARG_PROGRAM == $PROGRAM_CLIENT ]]; then
    PPRO_PLATFORM_PROGRAM_COMMAND_RUN_VENV_PYTHON=$MARKET_ENGINE_VENV_BIN_CLIENT_X86_64_LINUX/python3
    PPRO_PLATFORM_PROGRAM_ACTIVATE_VENV=$MARKET_ENGINE_VENV_BIN_CLIENT_X86_64_LINUX/activate
    PPRO_ZIP_DIR_PATH=$ZIPDIR_CLIENT_LINUX_X86_64
    PPRO_ZIP_ARCHIVE_PATH=$ZIP_ARCHIVE_CLIENT_LINUX_X86_64_PATH

# WINDOWS + CLIENT
elif [[ $ARG_PLATFORM == $PLATFORM_WINDOWS_X86_64 && $ARG_PROGRAM == $PROGRAM_CLIENT ]]; then
    PPRO_PLATFORM_PROGRAM_COMMAND_RUN_VENV_PYTHON=$MARKET_ENGINE_VENV_BIN_CLIENT_X86_64_WINDOWS/python.exe
    PPRO_PLATFORM_PROGRAM_ACTIVATE_VENV=$MARKET_ENGINE_VENV_BIN_CLIENT_X86_64_WINDOWS/activate
    PPRO_ZIP_DIR_PATH=$ZIPDIR_CLIENT_WINDOWS_X86_64
    PPRO_ZIP_ARCHIVE_PATH=$ZIP_ARCHIVE_CLIENT_WINDOWS_X86_64_PATH

# LINUX + API
elif [[ $ARG_PLATFORM == $PLATFORM_LINUX_X86_64 && $ARG_PROGRAM == $PROGRAM_API ]]; then
    PPRO_PLATFORM_PROGRAM_COMMAND_RUN_VENV_PYTHON=$MARKET_ENGINE_VENV_BIN_API_X86_64_LINUX/python3
    PPRO_PLATFORM_PROGRAM_ACTIVATE_VENV=$MARKET_ENGINE_VENV_BIN_API_X86_64_LINUX/activate
    PPRO_ZIP_DIR_PATH=$ZIPDIR_API_LINUX_X86_64
    PPRO_ZIP_ARCHIVE_PATH=$ZIP_ARCHIVE_API_LINUX_X86_64_PATH

# WINDOWS + API
elif [[ $ARG_PLATFORM == $PLATFORM_WINDOWS_X86_64 && $ARG_PROGRAM == $PROGRAM_API ]]; then
    PPRO_PLATFORM_PROGRAM_COMMAND_RUN_VENV_PYTHON=$MARKET_ENGINE_VENV_BIN_API_X86_64_WINDOWS/python.exe
    PPRO_PLATFORM_PROGRAM_ACTIVATE_VENV=$MARKET_ENGINE_VENV_BIN_API_X86_64_WINDOWS/activate
    PPRO_ZIP_DIR_PATH=$ZIPDIR_API_WINDOWS_X86_64
    PPRO_ZIP_ARCHIVE_PATH=$ZIP_ARCHIVE_API_WINDOWS_X86_64_PATH
fi