#!/bin/bash

HERE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
UTILS_PATH=$HERE/../utils
source $UTILS_PATH/platform_program_commands.sh PROGRAM=CLIENT $@

./check_make_binaries.sh $@ PROGRAM=CLIENT

echo ""
echo "--- CLEANING ---"

rm -rf $PPRO_ZIP_DIR_PATH/*
mkdir $PPRO_ZIP_DIR_PATH/bin
mkdir -p $PPRO_ZIP_DIR_PATH/usr/lib
mkdir -p $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
mkdir -p $PPRO_ZIP_DIR_PATH/LICENCES_MARKET_ENGINE_CLIENT

echo ""
echo "--- COPYING FILES ---"
echo ""

cp -r $PPRO_CLIENT_APPLICATION_BUILD/dist/* $PPRO_ZIP_DIR_PATH/bin
cp -r $PPRO_CLIENT_SONAR_BUILD/dist/* $PPRO_ZIP_DIR_PATH/bin
cp -r $PPRO_CLIENT_ENGINE_BUILD/engine $PPRO_ZIP_DIR_PATH/bin
cp -r $PPRO_CLIENT_LAUNCHER_BUILD/dist/* $PPRO_ZIP_DIR_PATH

cp $PPRO_CLIENT_ENGINE_BUILD_LIB/* $PPRO_ZIP_DIR_PATH/usr/lib

cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_MARKET_ENGINE_CLIENT/* $PPRO_ZIP_DIR_PATH/LICENCES_MARKET_ENGINE_CLIENT
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCE_SystemHud.txt $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCE_libgomp*.txt $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCE_OpenSSL.txt $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCE_RapidJson.txt $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCE_SystemHud.txt $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY
cp $MARKET_ENGINE_SHELL_DIST_LICENCES_PATH/LICENCES_THIRD_PARTY/LICENCES_PIP_Client.json $PPRO_ZIP_DIR_PATH/LICENCES_THIRD_PARTY

echo "--- CREATING ZIP ARCHIVE ---"
echo ""

rm $PPRO_ZIP_ARCHIVE_PATH
7z a $PPRO_ZIP_ARCHIVE_PATH $PPRO_ZIP_DIR_PATH
